application: plt-belay
version: 1
runtime: python
api_version: 1

handlers:

- url: /glogin
  script: plt-belay.py
  login: required

- url: /(.*\.(html|css|js))
  static_files: \1
  upload: (.*\.(html|css|js))

- url: /.*
  script: plt-belay.py

